@startuml activity_reset_memory
scale 1.5
skinparam {
    shadowing false
    linetype ortho
    defaultFontSize 10
    padding 1
}

skinparam activity {
    BackgroundColor #E1F5FE
    BorderColor #03A9F4
    FontSize 7
}

title Сброс памяти

start
:Нажать "Сбросить";
:MemoryModel.reset();
:Заблокировать мьютекс;
:Заполнить нулями;
:Разблокировать мьютекс;
:FaultInjector.reset();
:Отправить dataChanged();
:Очистить результаты\nи сбросить прогресс;
:Обновить UI;
stop

@enduml
