@startuml usecase_diagram
scale 1.5
skinparam {
    shadowing false
    linetype ortho
    defaultFontSize 10
    padding 1
}

left to right direction

title Use Case

actor User

rectangle "Управление" {
    usecase "Внедрить\nнеисправность" as UC1
    usecase "Сбросить\nпамять" as UC2
    usecase "Выбрать\nмодель" as UC3
}

rectangle "Тестирование" {
    usecase "Запустить\nтест" as UC4
    usecase "Выбрать\nалгоритм" as UC5
    usecase "Просмотреть\nрезультаты" as UC6
}

rectangle "Визуализация" {
    usecase "Просмотреть\nтаблицу" as UC7
    usecase "Просмотреть\nстатистику" as UC8
    usecase "Изменить\nтему" as UC9
}

User --> UC1
User --> UC2
User --> UC4
User --> UC6
User --> UC7
User --> UC8
User --> UC9

UC1 ..> UC3 : <<include>>
UC4 ..> UC5 : <<include>>

@enduml
